kind: BuildingKind
spec:
  category: custom
  name: Red Base
  description: This is the red base
  model: 17-03
  color: 4
  contract:
    file: ../contracts/RedBase.sol
  plugin:
    file: ../js/RedBase.js
  materials:
    - name: Red Goo
      quantity: 100
    - name: Green Goo
      quantity: 100
    - name: Blue Goo
      quantity: 100
